name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.0.2'
    - name: Cabal install split
      run: cabal install --lib split
    - name: Make
      run: make Render
    - uses: actions/upload-artifact@v2
      with:
        name: render.elf
        path: Render
